// Code generated by "enumer -type=Enum -values --transform=snake -trimprefix=Enum"; DO NOT EDIT.

package test

import (
	"fmt"
	"strings"
)

const _EnumName = "onetwothree"

var _EnumIndex = [...]uint8{0, 3, 6, 11}

const _EnumLowerName = "onetwothree"

func (i Enum) String() string {
	if i < 0 || i >= Enum(len(_EnumIndex)-1) {
		return fmt.Sprintf("Enum(%d)", i)
	}
	return _EnumName[_EnumIndex[i]:_EnumIndex[i+1]]
}

func (Enum) Values() []string {
	return EnumStrings()
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _EnumNoOp() {
	var x [1]struct{}
	_ = x[EnumOne-(0)]
	_ = x[EnumTwo-(1)]
	_ = x[EnumThree-(2)]
}

var _EnumValues = []Enum{EnumOne, EnumTwo, EnumThree}

var _EnumNameToValueMap = map[string]Enum{
	_EnumName[0:3]:       EnumOne,
	_EnumLowerName[0:3]:  EnumOne,
	_EnumName[3:6]:       EnumTwo,
	_EnumLowerName[3:6]:  EnumTwo,
	_EnumName[6:11]:      EnumThree,
	_EnumLowerName[6:11]: EnumThree,
}

var _EnumNames = []string{
	_EnumName[0:3],
	_EnumName[3:6],
	_EnumName[6:11],
}

// EnumString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func EnumString(s string) (Enum, error) {
	if val, ok := _EnumNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _EnumNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Enum values", s)
}

// EnumValues returns all values of the enum
func EnumValues() []Enum {
	return _EnumValues
}

// EnumStrings returns a slice of all String values of the enum
func EnumStrings() []string {
	strs := make([]string, len(_EnumNames))
	copy(strs, _EnumNames)
	return strs
}

// IsAEnum returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Enum) IsAEnum() bool {
	for _, v := range _EnumValues {
		if i == v {
			return true
		}
	}
	return false
}
